[package]
name = "netidx-lite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = "4"
env_logger = "0.11"
fxhash = "0.2"
log = "0.4"
parking_lot = "0.12"
tokio = { version = "1", features = ["full"] }
